- alias: Dining room lamp on with smart switch
  description: ""
  mode: single
  triggers:
    - trigger: state
      entity_id: light.smart_wi_fi_switch
      to: "on"
  conditions: []
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.dining_room_lamp_socket_1
      data: {}
